name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]
        architecture: [x64, x32, arm64, armhf]
        exclude:
          - os: macos-latest
            architecture: x32
          - os: macos-latest
            architecture: armhf
          - python-version: 3.1
          - os: macos-latest
            python-version: 3.6
            architecture: arm64
          - os: macos-latest
            python-version: 3.6
            architecture: x64
          - os: macos-latest
            python-version: 3.7
            architecture: arm64
          - os: macos-latest
            python-version: 3.7
            architecture: x64
          - os: macos-latest
            python-version: 3.11
            architecture: x64
          - os: macos-latest
            python-version: 3.8
            architecture: arm64
          - os: macos-latest
            python-version: 3.8
            architecture: x64
          - os: macos-latest
            python-version: 3.9
            architecture: arm64
          - os: ubuntu-latest
            python-version: 3.11
            architecture: arm64
          - os: ubuntu-latest
            python-version: 3.11
            architecture: armhf
          - os: ubuntu-latest
            python-version: 3.11
            architecture: x32
          - os: ubuntu-latest
            python-version: 3.6
            architecture: x32
          - os: ubuntu-latest
            python-version: 3.6
            architecture: armhf
          - os: ubuntu-latest
            python-version: 3.6
            architecture: x64
          - os: ubuntu-latest
            python-version: 3.6
            architecture: arm64
          - os: ubuntu-latest
            python-version: 3.7
            architecture: arm64
          - os: ubuntu-latest
            python-version: 3.8
            architecture: arm64
          - os: ubuntu-latest
            python-version: 3.8
            architecture: x32
          - os: ubuntu-latest
            python-version: 3.8
            architecture: armhf
          - os: ubuntu-latest
            python-version: 3.7
            architecture: armhf
          - os: ubuntu-latest
            python-version: 3.7
            architecture: x32
          - os: ubuntu-latest
            python-version: 3.7
            architecture: x64
          - os: ubuntu-latest
            python-version: 3.9
            architecture: arm64
          - os: ubuntu-latest
            python-version: 3.9
            architecture: armhf
          - os: ubuntu-latest
            python-version: 3.9
            architecture: x32
          - os: ubuntu-latest
            python-version: 3.9
            architecture: x64
          - os: windows-latest
            python-version: 3.6
            architecture: armhf
          - os: windows-latest
            python-version: 3.6
            architecture: arm64
          - os: windows-latest
            python-version: 3.6
            architecture: x64
          - os: windows-latest
            python-version: 3.6
            architecture: x32
          - os: windows-latest
            python-version: 3.7
            architecture: arm64
          - os: windows-latest
            python-version: 3.7
            architecture: armhf
          - os: windows-latest
            python-version: 3.7
            architecture: x64
          - os: windows-latest
            python-version: 3.7
            architecture: x32
          - os: windows-latest
            python-version: 3.8
            architecture: arm64
          - os: windows-latest
            python-version: 3.8
            architecture: armhf
          - os: windows-latest
            python-version: 3.8
            architecture: x64
          - os: windows-latest
            python-version: 3.8
            architecture: x32
          - os: windows-latest
            python-version: 3.9
            architecture: arm64
          - os: windows-latest
            python-version: 3.9
            architecture: armhf
          - os: windows-latest
            python-version: 3.9
            architecture: x64
          - os: windows-latest
            python-version: 3.9
            architecture: x32

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python for x64 and arm64
      if: matrix.architecture != 'x32' && matrix.architecture != 'armhf'
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python for x32 on Windows
      if: matrix.os == 'windows-latest' && matrix.architecture == 'x32'
      run: |
        choco install python --version=${{ matrix.python-version }} --x86
        python -m pip install --upgrade pip

    - name: Install dependencies for x32 on Ubuntu
      if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'x32'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y python${{ matrix.python-version }}:i386
        sudo ln -s /usr/bin/python${{ matrix.python-version }} /usr/bin/python3
        python3 -m pip install --upgrade pip

    - name: Install dependencies for arm64 on Ubuntu
      if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'arm64'
      run: |
        sudo apt-get update
        sudo apt-get install -y python${{ matrix.python-version }}:arm64
        sudo ln -s /usr/bin/python${{ matrix.python-version }} /usr/bin/python3
        python3 -m pip install --upgrade pip

    - name: Install dependencies for armhf on Ubuntu
      if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'armhf'
      run: |
        sudo dpkg --add-architecture armhf
        sudo apt-get update
        sudo apt-get install -y python${{ matrix.python-version }}:armhf
        sudo ln -s /usr/bin/python${{ matrix.python-version }} /usr/bin/python3
        python3 -m pip install --upgrade pip

    - name: Install dependencies for macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install openblas
        brew install gcc
        brew install qt  # Add this line to install qt
        brew install cmake  # Add this line to install cmake
        brew install python@${{ matrix.python-version }}
        python${{ matrix.python-version }} -m pip install --upgrade pip
        python${{ matrix.python-version }} -m pip install --upgrade setuptools wheel
        if [ -f requirements.txt ]; then python${{ matrix.python-version }} -m pip install -r requirements.txt; fi
        export LDFLAGS="-L/usr/local/opt/openblas/lib"
        export CPPFLAGS="-I/usr/local/opt/openblas/include"
        export PATH="/usr/local/opt/gcc/bin:$PATH"
        export MACOSX_DEPLOYMENT_TARGET="10.15"   
    # Install dependencies FOR Windows
    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
    # Install dependencies FOR Mac and Linux
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    

    # Build executable for Windows
    - name: Build executable for Windows
      if: matrix.os == 'windows-latest'
      run: |
        pip install pyinstaller
        if (Test-Path 'AL_CODON_APP.spec') { pyinstaller AL_CODON_APP.spec } else { pyinstaller --onefile --windowed --name AL_CODON_APP interface_AL_Counter.py }
        # Specify the path to Inno Setup compiler
        $innosetup = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
        & $innosetup 'F:\AL CODON APP FINAL VERSION\AL_CODON_APP.iss'

    # Build executable for macOS
    - name: Build executable for macOS
      if: matrix.os == 'macos-latest'
      run: |
        chmod +x build_mac.sh
        ./build_mac.sh

    # Build executable for Linux
    - name: Install pyinstaller and makeself for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
         sudo apt-get update
         sudo apt-get install -y makeself
         python -m pip install pyinstaller
         
    - name: Build executable for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
         chmod +x build_linux.sh
         ./build_linux.sh
         
    # Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-application-${{ matrix.os }}-${{ matrix.architecture }}-python-${{ matrix.python-version }}
        path: |
          dist/*
          build/*.run
          build/*.pkg

   # Post Install dependencies for Windows
    - name: Post Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    # Post Install dependencies for non-Windows
    - name: Post Install dependencies (Non-Windows)
      if: matrix.os != 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
